CREATE USER tiffanie WITH PASSWORD '1q2w3e4r!!';
CREATE DATABASE mw;
GRANT ALL PRIVILEGES ON DATABASE mw TO tiffanie;
ALTER DATABASE mw OWNER TO tiffanie;
CREATE DATABASE prefect;
GRANT ALL PRIVILEGES ON DATABASE prefect TO tiffanie;
ALTER DATABASE prefect OWNER TO tiffanie;
