# Base Image
FROM python:3.12.4-slim-bookworm

# Set working directory
WORKDIR /app

# Install git and other dependencies
RUN apt-get update && apt-get install -y git && apt-get clean

# Copy necessary files
COPY requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# The base image does not define a CMD or ENTRYPOINT
# It will be defined in the final image Dockerfile