"""empty message

Revision ID: 0840d08668e5
Revises: 13bded0cc4d4
Create Date: 2022-07-13 16:50:05.245109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0840d08668e5'
down_revision = '13bded0cc4d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mw_web_change_history', 'mw_web_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mw_web_domain','mw_web_vhost_id', nullable=False)
    op.create_unique_constraint(None, 'mw_web_domain', ['mw_web_vhost_id', 'domain_name', 'port'])
    op.create_foreign_key(None, 'mw_web_domain', 'mw_web_vhost', ['mw_web_vhost_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mw_web_domain', 'vhost_id')
    op.drop_column('mw_web_domain', 'jsv_port')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web_domain', sa.Column('jsv_port', sa.INTEGER(), autoincrement=False, nullable=False, comment='JSV Port'))
    op.add_column('mw_web_domain', sa.Column('vhost_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='Virtual Host ID'))
    op.drop_constraint(None, 'mw_web_domain', type_='foreignkey')
    op.drop_constraint(None, 'mw_web_domain', type_='unique')
    op.alter_column('mw_web_domain', 'mw_web_vhost_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mw_web_change_history', 'mw_web_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mw_web', 'port',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='Port')
    # ### end Alembic commands ###
