"""empty message

Revision ID: 0991aa2c6131
Revises: 55027812a327
Create Date: 2022-08-01 09:43:22.210076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0991aa2c6131'
down_revision = '55027812a327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ut_tag', sa.Column('value1', sa.String(length=100), nullable=True, comment='부가정보1'))
    op.add_column('ut_tag', sa.Column('value2', sa.String(length=100), nullable=True, comment='부가정보2'))
    op.alter_column('ut_tag_km', 'value1',
               existing_type=sa.VARCHAR(length=100),
               comment='부가정보1',
               existing_comment='부자정보1',
               existing_nullable=True)
    op.alter_column('ut_tag_km', 'value2',
               existing_type=sa.VARCHAR(length=100),
               comment='부가정보2',
               existing_comment='부자정보2',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ut_tag_km', 'value2',
               existing_type=sa.VARCHAR(length=100),
               comment='부자정보2',
               existing_comment='부가정보2',
               existing_nullable=True)
    op.alter_column('ut_tag_km', 'value1',
               existing_type=sa.VARCHAR(length=100),
               comment='부자정보1',
               existing_comment='부가정보1',
               existing_nullable=True)
    op.drop_column('ut_tag', 'value2')
    op.drop_column('ut_tag', 'value1')
    # ### end Alembic commands ###
