"""empty message

Revision ID: 09ec291c0b8c
Revises: 0cbea1758c5c
Create Date: 2021-09-13 11:27:08.950946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ec291c0b8c'
down_revision = '0cbea1758c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was_webtobconnector', sa.Column('real_web_host_id', sa.String(length=30), nullable=True, comment='Web서버 HOST ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_was_webtobconnector', 'real_web_host_id')
    # ### end Alembic commands ###
