"""empty message

Revision ID: 0cbea1758c5c
Revises: 0e67fa82860b
Create Date: 2021-09-06 09:18:38.387643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbea1758c5c'
down_revision = '0e67fa82860b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_app_master', sa.Column('description', sa.String(length=500), nullable=True, comment='설명'))
    op.alter_column('mw_app_master', 'app_name',
               existing_type=sa.VARCHAR(length=200),
               comment='appliaction 명칭',
               existing_comment='appliaction 설명',
               existing_nullable=True)
    op.alter_column('mw_db_master', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='설명',
               existing_comment='DB 설명',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mw_db_master', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='DB 설명',
               existing_comment='설명',
               existing_nullable=True)
    op.alter_column('mw_app_master', 'app_name',
               existing_type=sa.VARCHAR(length=200),
               comment='appliaction 설명',
               existing_comment='appliaction 명칭',
               existing_nullable=True)
    op.drop_column('mw_app_master', 'description')
    # ### end Alembic commands ###
