"""empty message

Revision ID: 0e67fa82860b
Revises: 575870c8a374
Create Date: 2021-09-03 11:54:34.939345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e67fa82860b'
down_revision = '575870c8a374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'mo_grid_config',
        'Table 조회 Configuration',
        existing_comment=None,
        schema=None
    )
    op.add_column('mw_server', sa.Column('dr_host_id', sa.String(length=30), nullable=True, comment='DR HOST ID'))
    op.add_column('mw_was', sa.Column('use_yn', sa.Enum('YES', 'NO', name='ynenum'), server_default='YES', nullable=False, comment='사용여부'))
    op.add_column('mw_was_instance', sa.Column('app_id', sa.String(length=50), nullable=True, comment='application id'))
    op.execute("UPDATE mw_was_instance set app_id = 'NOAPP'")
    op.alter_column('mw_was_instance','app_id', nullable=False)
    op.create_foreign_key(None, 'mw_was_instance', 'mw_app_master', ['app_id'], ['app_id'])
    op.add_column('mw_web', sa.Column('use_yn', sa.Enum('YES', 'NO', name='ynenum'), server_default='YES', nullable=False, comment='사용여부'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'use_yn')
    op.drop_constraint(None, 'mw_was_instance', type_='foreignkey')
    op.drop_column('mw_was_instance', 'app_id')
    op.drop_column('mw_was', 'use_yn')
    op.drop_column('mw_server', 'dr_host_id')
    op.drop_table_comment(
        'mo_grid_config',
        existing_comment='Table 조회 Configuration',
        schema=None
    )
    # ### end Alembic commands ###
