"""empty message

Revision ID: 0e6f4d12b5ae
Revises: a4f8986fed83
Create Date: 2021-11-16 18:47:52.630327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6f4d12b5ae'
down_revision = 'a4f8986fed83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web_domain', sa.Column('file_update_dt', sa.DateTime(), nullable=True))
    op.add_column('mw_web_domain', sa.Column('domain_update_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web_domain', 'domain_update_dt')
    op.drop_column('mw_web_domain', 'file_update_dt')
    # ### end Alembic commands ###
