"""empty message

Revision ID: 0f62930ed99d
Revises: 88ddc041371a
Create Date: 2022-05-11 17:22:51.832174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f62930ed99d'
down_revision = '88ddc041371a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_command_master', sa.Column('kafka_yn', sa.Enum('YES', 'NO', name='ynenum'), server_default='NO', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_command_master', 'kafka_yn')
    # ### end Alembic commands ###
