"""empty message

Revision ID: 13d559c44aba
Revises: 8f7adbd688c9
Create Date: 2023-05-16 09:01:13.680679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d559c44aba'
down_revision = '8f7adbd688c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ut_html_content', sa.Column('search_tags', sa.String(length=500), nullable=True, comment='SEARCH TAGS'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ut_html_content', 'search_tags')
    # ### end Alembic commands ###
