"""empty message

Revision ID: 18dcfe9789d8
Revises: 9dc60c0552e2
Create Date: 2022-07-26 17:28:42.375172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18dcfe9789d8'
down_revision = '9dc60c0552e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was_change_history', sa.Column('mw_was_id', sa.Integer(), nullable=True))
    op.drop_constraint('mw_was_change_history_was_id_create_on_key', 'mw_was_change_history', type_='unique')
    op.execute("update mw_was_change_history a set mw_was_id = (select id from mw_was where was_id = a.was_id)")
    op.create_unique_constraint(None, 'mw_was_change_history', ['mw_was_id', 'create_on'])
    op.drop_constraint('mw_was_change_history_was_id_fkey', 'mw_was_change_history', type_='foreignkey')
    op.create_foreign_key(None, 'mw_was_change_history', 'mw_was', ['mw_was_id'], ['id'], ondelete='CASCADE')
    op.drop_column('mw_was_change_history', 'was_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was_change_history', sa.Column('was_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False, comment='WAS domain id'))
    op.drop_constraint(None, 'mw_was_change_history', type_='foreignkey')
    op.create_foreign_key('mw_was_change_history_was_id_fkey', 'mw_was_change_history', 'mw_was', ['was_id'], ['was_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'mw_was_change_history', type_='unique')
    op.create_unique_constraint('mw_was_change_history_was_id_create_on_key', 'mw_was_change_history', ['was_id', 'create_on'])
    op.drop_column('mw_was_change_history', 'mw_was_id')
    # ### end Alembic commands ###
