"""empty message

Revision ID: 1b9a60be7349
Revises: ef965f895a4b
Create Date: 2021-06-11 17:18:40.837351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b9a60be7349'
down_revision = 'ef965f895a4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_result', sa.Column('result_hash', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_result', 'result_hash')
    # ### end Alembic commands ###
