"""empty message

Revision ID: 25bd22f68d1b
Revises: 683a44758e1f
Create Date: 2022-11-24 16:37:53.416674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25bd22f68d1b'
down_revision = '683a44758e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mo_test')
    op.add_column('ag_agent', sa.Column('refresh_token', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_agent', 'refresh_token')
    op.create_table('mo_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('array_test', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mo_test_pkey')
    )
    # ### end Alembic commands ###
