"""empty message

Revision ID: 2d7cc3818593
Revises: 612ecef894f4
Create Date: 2021-07-20 07:59:40.118090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2d7cc3818593'
down_revision = '612ecef894f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_agent', sa.Column('landscape', postgresql.ENUM('PROD', 'TEST', 'DEV', 'DR', name='locationenum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_agent', 'landscape')
    # ### end Alembic commands ###
