"""empty message

Revision ID: 43304da02272
Revises: 0f62930ed99d
Create Date: 2022-05-18 15:18:15.781375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43304da02272'
down_revision = '0f62930ed99d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_command_master', sa.Column('command_sender', sa.Enum('SERVER', 'KAFKA', 'SERVER_N_KAFKA', name='targettosendenum'), server_default='SERVER', nullable=False))
    op.add_column('ag_command_master', sa.Column('result_receiver', sa.Enum('SERVER', 'KAFKA', 'SERVER_N_KAFKA', name='targettosendenum'), server_default='SERVER', nullable=False))
    op.add_column('ag_command_master', sa.Column('target_object', sa.String(length=50), nullable=True))
    op.drop_column('ag_command_master', 'kafka_yn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_command_master', sa.Column('kafka_yn', postgresql.ENUM('YES', 'NO', name='ynenum'), server_default=sa.text("'NO'::ynenum"), autoincrement=False, nullable=False))
    op.drop_column('ag_command_master', 'target_object')
    op.drop_column('ag_command_master', 'result_receiver')
    op.drop_column('ag_command_master', 'command_sender')
    # ### end Alembic commands ###
