"""empty message

Revision ID: 4645cbf7d87e
Revises: 5d6c337b8e6e
Create Date: 2022-07-01 18:54:39.422658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4645cbf7d87e'
down_revision = '5d6c337b8e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was_instance', sa.Column('resource_tag', sa.String(length=500), server_default='dummy', nullable=True, comment='Resource Tag'))
    op.execute("UPDATE mw_was_instance set resource_tag = 'dummy'")
    op.alter_column('mw_was_instance','resource_tag', nullable=False)

    op.create_foreign_key(None, 'mw_was_instance', 'ut_resource_tag', ['resource_tag'], ['tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_was_instance', type_='foreignkey')
    op.drop_column('mw_was_instance', 'resource_tag')
    # ### end Alembic commands ###
