"""empty message

Revision ID: 4cca9c6bd5ef
Revises: 43304da02272
Create Date: 2022-06-29 13:06:05.047612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cca9c6bd5ef'
down_revision = '43304da02272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_agent', sa.Column('installation_path', sa.String(length=300), nullable=True, comment='Installation Path'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_agent', 'installation_path')
    # ### end Alembic commands ###
