"""empty message

Revision ID: 52d2b8917a20
Revises: 58da04c08b80
Create Date: 2021-07-29 16:40:32.985821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d2b8917a20'
down_revision = '58da04c08b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('system_user', sa.String(length=50), nullable=True))
    op.add_column('mw_web', sa.Column('system_user', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'system_user')
    op.drop_column('mw_was', 'system_user')
    # ### end Alembic commands ###
