"""empty message

Revision ID: 55027812a327
Revises: ea9d96f3f6fd
Create Date: 2022-07-29 15:15:49.231379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55027812a327'
down_revision = 'ea9d96f3f6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web', sa.Column('version_info', sa.Text(), nullable=True, comment='Version 정보'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'version_info')
    # ### end Alembic commands ###
