"""empty message

Revision ID: 567931851832
Revises: f311ae21288c
Create Date: 2021-06-04 19:46:43.644168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567931851832'
down_revision = 'f311ae21288c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_result', sa.Column('complited_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_result', 'complited_date')
    # ### end Alembic commands ###
