"""empty message

Revision ID: 56fc2802d178
Revises: 13d559c44aba
Create Date: 2024-01-23 12:01:11.578094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fc2802d178'
down_revision = '13d559c44aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ut_html_content', sa.Column('group_id', sa.String(length=50), nullable=True))
    op.add_column('ut_md_content', sa.Column('group_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ut_md_content', 'group_id')
    op.drop_column('ut_html_content', 'group_id')
    # ### end Alembic commands ###
