"""empty message

Revision ID: 58da04c08b80
Revises: b95a706867ec
Create Date: 2021-07-22 11:38:52.346812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58da04c08b80'
down_revision = 'b95a706867ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_biz_category', sa.Column('user_name_incharge', sa.String(length=50), nullable=True))
    op.add_column('mw_biz_category', sa.Column('user_id_incharge', sa.String(length=50), nullable=True))
    op.add_column('mw_biz_category', sa.Column('user_id', sa.String(length=50), nullable=False))
    op.add_column('mw_biz_category', sa.Column('create_on', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_biz_category', 'create_on')
    op.drop_column('mw_biz_category', 'user_id')
    op.drop_column('mw_biz_category', 'user_id_incharge')
    op.drop_column('mw_biz_category', 'user_name_incharge')
    # ### end Alembic commands ###
