"""empty message

Revision ID: 5d6c337b8e6e
Revises: 8164c739674f
Create Date: 2022-06-30 13:30:46.053494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6c337b8e6e'
down_revision = '8164c739674f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_agent', sa.Column('resource_tag', sa.String(length=500), server_default='dummy', nullable=True, comment='Resource Tag'))
    op.execute("UPDATE ag_agent set resource_tag = 'dummy'")
    op.alter_column('ag_agent','resource_tag', nullable=False)

    op.create_foreign_key(None, 'ag_agent', 'ut_resource_tag', ['resource_tag'], ['tag'])
    op.add_column('mw_web', sa.Column('resource_tag', sa.String(length=500), server_default='dummy', nullable=True, comment='Resource Tag'))
    op.execute("UPDATE mw_web set resource_tag = 'dummy'")
    op.alter_column('mw_web','resource_tag', nullable=False)

    op.create_foreign_key(None, 'mw_web', 'ut_resource_tag', ['resource_tag'], ['tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_web', type_='foreignkey')
    op.drop_column('mw_web', 'resource_tag')
    op.drop_constraint(None, 'ag_agent', type_='foreignkey')
    op.drop_column('ag_agent', 'resource_tag')
    # ### end Alembic commands ###
