"""empty message

Revision ID: 5e2308353448
Revises: 72f1db585542
Create Date: 2021-08-23 15:59:37.572630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2308353448'
down_revision = '72f1db585542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo_grid_config', sa.Column('condition_columns', sa.String(length=500), nullable=True))
    op.add_column('mw_was_webtobconnector', sa.Column('disable_pipe', sa.Enum('YES', 'NO', name='ynenum'), nullable=True))
    op.add_column('mw_web', sa.Column('dependent_was_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'dependent_was_id')
    op.drop_column('mw_was_webtobconnector', 'disable_pipe')
    op.drop_column('mo_grid_config', 'condition_columns')
    # ### end Alembic commands ###
