"""empty message

Revision ID: 612ecef894f4
Revises: ef4ada906784
Create Date: 2021-07-19 11:57:54.417996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612ecef894f4'
down_revision = 'ef4ada906784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ag_command_helper_mapping_key_target_file_name_agent_id_key', 'ag_command_helper', type_='unique')
    op.create_unique_constraint(None, 'ag_command_helper', ['mapping_key', 'target_file_name', 'agent_id', 'string_to_replace'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ag_command_helper', type_='unique')
    op.create_unique_constraint('ag_command_helper_mapping_key_target_file_name_agent_id_key', 'ag_command_helper', ['mapping_key', 'target_file_name', 'agent_id'])
    # ### end Alembic commands ###
