"""empty message

Revision ID: 683a44758e1f
Revises: 0991aa2c6131
Create Date: 2022-11-08 11:32:24.534333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683a44758e1f'
down_revision = '0991aa2c6131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('version_info', sa.Text(), nullable=True, comment='Version 정보'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_was', 'version_info')
    # ### end Alembic commands ###
