"""empty message

Revision ID: 7412a658f0a8
Revises: 0840d08668e5
Create Date: 2022-07-18 16:18:43.380797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7412a658f0a8'
down_revision = '0840d08668e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo_grid_config', sa.Column('seperator', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo_grid_config', 'seperator')
    # ### end Alembic commands ###
