"""empty message

Revision ID: 78208b8908e7
Revises: 3ffdbfe49bc5
Create Date: 2022-07-19 12:52:19.646662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78208b8908e7'
down_revision = '3ffdbfe49bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo_grid_config', sa.Column('condition_labels', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo_grid_config', 'condition_labels')
    # ### end Alembic commands ###
