"""empty message

Revision ID: 7c2bc0bd343a
Revises: 7c80a5fb06f7
Create Date: 2021-07-08 09:25:55.556844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c2bc0bd343a'
down_revision = '7c80a5fb06f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mo_was_instance_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.String(length=30), nullable=False),
    sa.Column('was_id', sa.String(length=30), nullable=False),
    sa.Column('was_instance_id', sa.String(length=30), nullable=False),
    sa.Column('was_instance_status', sa.Enum('RUNNING', 'STANDBY', 'SHUTDOWN', 'FAILED', name='wasinstancestatusenum'), nullable=False),
    sa.Column('landscape', postgresql.ENUM('PROD', 'TEST', 'DEV', 'DR', name='locationenum', create_type=False), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('update_on', sa.DateTime(), nullable=False),
    sa.Column('create_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['mw_server.host_id'], ),
    sa.ForeignKeyConstraint(['was_id'], ['mw_was.was_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_id', 'was_id', 'was_instance_id')
    )
    op.create_foreign_key(None, 'mw_was_httplistener', 'mw_was_instance', ['was_id', 'was_instance_id'], ['was_id', 'was_instance_id'])
    op.create_foreign_key(None, 'mw_was_webtobconnector', 'mw_was_instance', ['was_id', 'was_instance_id'], ['was_id', 'was_instance_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_was_webtobconnector', type_='foreignkey')
    op.drop_constraint(None, 'mw_was_httplistener', type_='foreignkey')
    op.drop_table('mo_was_instance_status')
    # ### end Alembic commands ###
