"""empty message

Revision ID: 7c80a5fb06f7
Revises: 1b9a60be7349
Create Date: 2021-07-02 10:14:21.429548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c80a5fb06f7'
down_revision = '1b9a60be7349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was_instance', sa.Column('engine_command', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_was_instance', 'engine_command')
    # ### end Alembic commands ###
