"""empty message

Revision ID: 8164c739674f
Revises: 4cca9c6bd5ef
Create Date: 2022-06-29 18:30:17.035858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8164c739674f'
down_revision = '4cca9c6bd5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('resource_tag', sa.String(length=500), nullable=True, comment='Resource Tag'))
    op.execute("UPDATE mw_was set resource_tag = 'dummy'")
    op.alter_column('mw_was','resource_tag', nullable=False)
    op.create_foreign_key(None, 'mw_was', 'ut_resource_tag', ['resource_tag'], ['tag'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_was', type_='foreignkey')
    op.drop_column('mw_was', 'resource_tag')
    # ### end Alembic commands ###
