"""empty message

Revision ID: 8487825ad641
Revises: 78208b8908e7
Create Date: 2022-07-19 14:09:46.434550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8487825ad641'
down_revision = '78208b8908e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ut_tag', sa.Column('label', sa.String(length=100), nullable=True, comment='LABEL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ut_tag', 'label')
    # ### end Alembic commands ###
