"""empty message

Revision ID: 88ddc041371a
Revises: e6e32c59b540
Create Date: 2022-05-10 14:24:43.058087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ddc041371a'
down_revision = 'e6e32c59b540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('jeus_properties_update_date', sa.DateTime(), nullable=True, comment='jeus properties 정보 갱신일시'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_was', 'jeus_properties_update_date')
    # ### end Alembic commands ###
