"""empty message

Revision ID: 8ef4154b7a26
Revises: 09ec291c0b8c
Create Date: 2021-11-02 12:35:37.478775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef4154b7a26'
down_revision = '09ec291c0b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gt_group_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=30), nullable=False),
    sa.Column('user_ids', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('create_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id'),
    comment='GitLab group id 별 user 매핑'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gt_group_users')
    # ### end Alembic commands ###
