"""empty message

Revision ID: 9841843bf02a
Revises: 4645cbf7d87e
Create Date: 2022-07-04 12:11:23.400370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9841843bf02a'
down_revision = '4645cbf7d87e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_agent','resource_tag')
    op.add_column('ag_agent', sa.Column('resource_tag', sa.Integer, server_default='1', nullable=False, comment='Resource Tag'))
    op.create_foreign_key(None, 'ag_agent', 'ut_resource_tag', ['resource_tag'], ['id'])

    op.drop_column('mw_was','resource_tag')
    op.add_column('mw_was', sa.Column('resource_tag', sa.Integer, server_default='1', nullable=False, comment='Resource Tag'))
    op.create_foreign_key(None, 'mw_was', 'ut_resource_tag', ['resource_tag'], ['id'])

    op.drop_column('mw_was_instance','resource_tag')
    op.add_column('mw_was_instance', sa.Column('resource_tag', sa.Integer, server_default='1', nullable=False, comment='Resource Tag'))
    op.create_foreign_key(None, 'mw_was_instance', 'ut_resource_tag', ['resource_tag'], ['id'])

    op.drop_column('mw_web','resource_tag')
    op.add_column('mw_web', sa.Column('resource_tag', sa.Integer, server_default='1', nullable=False, comment='Resource Tag'))
    op.create_foreign_key(None, 'mw_web', 'ut_resource_tag', ['resource_tag'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mw_web', type_='foreignkey')
    op.create_foreign_key('mw_web_resource_tag_fkey', 'mw_web', 'ut_resource_tag', ['resource_tag'], ['tag'])
    op.drop_constraint(None, 'mw_was_instance', type_='foreignkey')
    op.create_foreign_key('mw_was_instance_resource_tag_fkey', 'mw_was_instance', 'ut_resource_tag', ['resource_tag'], ['tag'])
    op.drop_constraint(None, 'mw_was', type_='foreignkey')
    op.create_foreign_key('mw_was_resource_tag_fkey', 'mw_was', 'ut_resource_tag', ['resource_tag'], ['tag'])
    op.drop_constraint(None, 'ag_agent', type_='foreignkey')
    op.create_foreign_key('ag_agent_resource_tag_fkey', 'ag_agent', 'ut_resource_tag', ['resource_tag'], ['tag'])
    # ### end Alembic commands ###
