"""empty message

Revision ID: 9dc60c0552e2
Revises: dd964df7ac1f
Create Date: 2022-07-21 13:08:22.303782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc60c0552e2'
down_revision = 'dd964df7ac1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mw_bizcategory_was')
    op.drop_table('mw_bizcategory_web')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mw_bizcategory_web',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_of_bizcategory', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_of_web', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_of_bizcategory'], ['mw_biz_category.id'], name='mw_bizcategory_web_id_of_bizcategory_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_of_web'], ['mw_web.id'], name='mw_bizcategory_web_id_of_web_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mw_bizcategory_web_pkey')
    )
    op.create_table('mw_bizcategory_was',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_of_bizcategory', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_of_was', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_of_bizcategory'], ['mw_biz_category.id'], name='mw_bizcategory_was_id_of_bizcategory_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_of_was'], ['mw_was.id'], name='mw_bizcategory_was_id_of_was_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='mw_bizcategory_was_pkey')
    )
    # ### end Alembic commands ###
