"""empty message

Revision ID: a103574c45bd
Revises: dc41af9f1af6
Create Date: 2021-08-06 10:54:27.562440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a103574c45bd'
down_revision = 'dc41af9f1af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_agent', sa.Column('agent_sub_type', sa.Enum('WIN_JEUS8', 'WIN_JEUS7', 'WIN_JEUS6', 'UNIX_JEUS6', 'UNIX_JEUS8', 'ETC', name='agentsubtypeenum'), nullable=True))
    op.create_foreign_key(None, 'ag_command_detail', 'ag_agent', ['agent_id'], ['agent_id'])
    op.add_column('ag_result', sa.Column('result_message', sa.Text(), nullable=True))
    op.create_index(op.f('ix_ag_result_complited_date'), 'ag_result', ['complited_date'], unique=False)
    op.create_index(op.f('ix_ag_result_create_on'), 'ag_result', ['create_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ag_result_create_on'), table_name='ag_result')
    op.drop_index(op.f('ix_ag_result_complited_date'), table_name='ag_result')
    op.drop_column('ag_result', 'result_message')
    op.drop_constraint(None, 'ag_command_detail', type_='foreignkey')
    op.drop_column('ag_agent', 'agent_sub_type')
    # ### end Alembic commands ###
