"""empty message

Revision ID: a1fa82217a89
Revises: 0e6f4d12b5ae
Create Date: 2021-11-24 12:58:45.812998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1fa82217a89'
down_revision = '0e6f4d12b5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web_domain', sa.Column('notbefore', sa.DateTime(), nullable=True, comment='유효기간시작'))
    op.add_column('mw_web_domain', sa.Column('notafter', sa.DateTime(), nullable=True, comment='유효기간만료'))
    op.add_column('mw_web_domain', sa.Column('subject', sa.String(length=300), nullable=True, comment='주제'))
    op.add_column('mw_web_domain', sa.Column('serial', sa.String(length=100), nullable=True, comment='일련번호'))
    op.add_column('mw_web_domain', sa.Column('issuer', sa.String(length=300), nullable=True, comment='발급자'))
    op.add_column('mw_web_domain', sa.Column('notbefore_ca', sa.DateTime(), nullable=True, comment='유효기간시작(CA)'))
    op.add_column('mw_web_domain', sa.Column('notafter_ca', sa.DateTime(), nullable=True, comment='유효기간만료(CA)'))
    op.add_column('mw_web_domain', sa.Column('subject_ca', sa.String(length=300), nullable=True, comment='주제(CA)'))
    op.add_column('mw_web_domain', sa.Column('serial_ca', sa.String(length=100), nullable=True, comment='일련번호(CA)'))
    op.add_column('mw_web_domain', sa.Column('issuer_ca', sa.String(length=300), nullable=True, comment='발급자(CA)'))
    op.add_column('mw_web_domain', sa.Column('update_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web_domain', 'update_dt')
    op.drop_column('mw_web_domain', 'issuer_ca')
    op.drop_column('mw_web_domain', 'serial_ca')
    op.drop_column('mw_web_domain', 'subject_ca')
    op.drop_column('mw_web_domain', 'notafter_ca')
    op.drop_column('mw_web_domain', 'notbefore_ca')
    op.drop_column('mw_web_domain', 'issuer')
    op.drop_column('mw_web_domain', 'serial')
    op.drop_column('mw_web_domain', 'subject')
    op.drop_column('mw_web_domain', 'notafter')
    op.drop_column('mw_web_domain', 'notbefore')
    # ### end Alembic commands ###
