"""empty message

Revision ID: a3e692668a62
Revises: a1fa82217a89
Create Date: 2021-11-26 13:01:54.006948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e692668a62'
down_revision = 'a1fa82217a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web_vhost', sa.Column('urlrewrite_yn', sa.Enum('YES', 'NO', name='ynenum'), nullable=True, comment='URL Rewrite 여부'))
    op.add_column('mw_web_vhost', sa.Column('urlrewrite_config', sa.String(length=200), nullable=True, comment='URL Rewrite config 파일 위치'))
    op.add_column('mw_web_vhost', sa.Column('urlrewrite_text', sa.Text(), nullable=True, comment='URL Rewrite config 파일 내용'))
    op.add_column('mw_web_vhost', sa.Column('urlrewrite_update_date', sa.DateTime(), nullable=True, comment='URL Rewrite 갱신일시'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web_vhost', 'urlrewrite_update_date')
    op.drop_column('mw_web_vhost', 'urlrewrite_text')
    op.drop_column('mw_web_vhost', 'urlrewrite_config')
    op.drop_column('mw_web_vhost', 'urlrewrite_yn')
    # ### end Alembic commands ###
