"""empty message

Revision ID: a4f8986fed83
Revises: 8ef4154b7a26
Create Date: 2021-11-16 15:50:39.227550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4f8986fed83'
down_revision = '8ef4154b7a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_autorun_result', sa.Column('autorun_param', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_autorun_result', 'autorun_param')
    # ### end Alembic commands ###
