"""empty message

Revision ID: aceecf2eda13
Revises: e63cc2f60c6c
Create Date: 2022-04-19 10:25:20.705870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aceecf2eda13'
down_revision = 'e63cc2f60c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('agent_id', sa.String(length=30), nullable=True, comment='MW Agent ID'))
    op.add_column('mw_web', sa.Column('agent_id', sa.String(length=30), nullable=True, comment='MW Agent ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'agent_id')
    op.drop_column('mw_was', 'agent_id')
    # ### end Alembic commands ###
