"""empty message

Revision ID: b95a706867ec
Revises: a744f38b64ef
Create Date: 2021-07-20 11:38:06.098731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b95a706867ec'
down_revision = 'a744f38b64ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web', sa.Column('newgeneration_yn', postgresql.ENUM('YES', 'NO', name='ynenum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'newgeneration_yn')
    # ### end Alembic commands ###
