"""empty message

Revision ID: c2b7aca1c0bd
Revises: a103574c45bd
Create Date: 2021-08-17 15:45:46.408044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b7aca1c0bd'
down_revision = 'a103574c45bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mo_grid_config', sa.Column('widths', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mo_grid_config', 'widths')
    # ### end Alembic commands ###
