"""empty message

Revision ID: d8cdc6f97128
Revises: 9841843bf02a
Create Date: 2022-07-11 13:39:43.621409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cdc6f97128'
down_revision = '9841843bf02a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web_vhost', sa.Column('ssl_name', sa.String(length=100), nullable=True, comment='SSL Name'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web_vhost', 'ssl_name')
    # ### end Alembic commands ###
