"""empty message

Revision ID: dc41af9f1af6
Revises: 52d2b8917a20
Create Date: 2021-07-30 13:10:43.137222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc41af9f1af6'
down_revision = '52d2b8917a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('running_type', sa.Enum('AA', 'AS', 'SA', name='runingtypeenum'), nullable=True))
    op.add_column('mw_was', sa.Column('standby_host_id', sa.String(length=30), nullable=True))
    op.add_column('mw_web', sa.Column('running_type', sa.Enum('AA', 'AS', 'SA', name='runingtypeenum'), nullable=True))
    op.add_column('mw_web', sa.Column('standby_host_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web', 'standby_host_id')
    op.drop_column('mw_web', 'running_type')
    op.drop_column('mw_was', 'standby_host_id')
    op.drop_column('mw_was', 'running_type')
    # ### end Alembic commands ###
