"""empty message

Revision ID: dd964df7ac1f
Revises: 8487825ad641
Create Date: 2022-07-20 14:47:37.884874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd964df7ac1f'
down_revision = '8487825ad641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ag_agent_resource_tag_fkey', 'ag_agent', type_='foreignkey')
    op.drop_column('ag_agent', 'resource_tag')
    op.drop_column('mw_biz_category', 'user_id_incharge')
    op.drop_column('mw_biz_category', 'user_name_incharge')
    op.drop_constraint('mw_was_resource_tag_fkey', 'mw_was', type_='foreignkey')
    op.drop_column('mw_was', 'user_name_incharge')
    op.drop_column('mw_was', 'user_id_incharge')
    op.drop_column('mw_was', 'resource_tag')
    op.drop_constraint('mw_was_instance_resource_tag_fkey', 'mw_was_instance', type_='foreignkey')
    op.drop_column('mw_was_instance', 'resource_tag')
    op.drop_constraint('mw_web_resource_tag_fkey', 'mw_web', type_='foreignkey')
    op.drop_column('mw_web', 'user_name_incharge')
    op.drop_column('mw_web', 'user_id_incharge')
    op.drop_column('mw_web', 'resource_tag')
    op.drop_table('ut_tag_resource_tag')
    op.drop_table('ut_resource_tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web', sa.Column('resource_tag', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='Resource Tag'))
    op.add_column('mw_web', sa.Column('user_id_incharge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('mw_web', sa.Column('user_name_incharge', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='담당자 이름'))
    op.create_foreign_key('mw_web_resource_tag_fkey', 'mw_web', 'ut_resource_tag', ['resource_tag'], ['id'])
    op.add_column('mw_was_instance', sa.Column('resource_tag', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='Resource Tag'))
    op.create_foreign_key('mw_was_instance_resource_tag_fkey', 'mw_was_instance', 'ut_resource_tag', ['resource_tag'], ['id'])
    op.add_column('mw_was', sa.Column('resource_tag', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='Resource Tag'))
    op.add_column('mw_was', sa.Column('user_id_incharge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('mw_was', sa.Column('user_name_incharge', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='담당자 이름'))
    op.create_foreign_key('mw_was_resource_tag_fkey', 'mw_was', 'ut_resource_tag', ['resource_tag'], ['id'])
    op.add_column('mw_biz_category', sa.Column('user_name_incharge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('mw_biz_category', sa.Column('user_id_incharge', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ag_agent', sa.Column('resource_tag', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False, comment='Resource Tag'))
    op.create_foreign_key('ag_agent_resource_tag_fkey', 'ag_agent', 'ut_resource_tag', ['resource_tag'], ['id'])
    op.create_table('ut_resource_tag',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ut_resource_tag_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Primary Key'),
    sa.Column('tag', sa.VARCHAR(length=500), autoincrement=False, nullable=False, comment='TAG'),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='리소스 원천'),
    sa.Column('use_yn', postgresql.ENUM('YES', 'NO', name='ynenum'), server_default=sa.text("'YES'::ynenum"), autoincrement=False, nullable=False, comment='사용여부'),
    sa.Column('user_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('create_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ut_resource_tag_pkey'),
    sa.UniqueConstraint('tag', name='ut_resource_tag_tag_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('ut_tag_resource_tag',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_of_tag', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_of_resource_tag', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_of_resource_tag'], ['ut_resource_tag.id'], name='ut_tag_resource_tag_id_of_resource_tag_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_of_tag'], ['ut_tag.id'], name='ut_tag_resource_tag_id_of_tag_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ut_tag_resource_tag_pkey')
    )
    # ### end Alembic commands ###
