"""empty message

Revision ID: e63cc2f60c6c
Revises: 1c6eb481d01a
Create Date: 2022-04-05 15:49:39.163427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e63cc2f60c6c'
down_revision = '1c6eb481d01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_was', sa.Column('license_text', sa.Text(), nullable=True, comment='License 정보'))
    op.add_column('mw_was', sa.Column('license_update_date', sa.DateTime(), nullable=True, comment='License 정보 갱신일시'))
    op.drop_column('mw_was', 'license_object')
    op.add_column('mw_web', sa.Column('license_text', sa.Text(), nullable=True, comment='License 정보'))
    op.add_column('mw_web', sa.Column('license_update_date', sa.DateTime(), nullable=True, comment='License 정보 갱신일시'))
    op.drop_column('mw_web', 'license_object')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web', sa.Column('license_object', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='License 정보'))
    op.drop_column('mw_web', 'license_update_date')
    op.drop_column('mw_web', 'license_text')
    op.add_column('mw_was', sa.Column('license_object', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='License 정보'))
    op.drop_column('mw_was', 'license_update_date')
    op.drop_column('mw_was', 'license_text')
    # ### end Alembic commands ###
