"""empty message

Revision ID: ea9d96f3f6fd
Revises: f54d868a559b
Create Date: 2022-07-29 11:29:02.394344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9d96f3f6fd'
down_revision = 'f54d868a559b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ut_file', sa.Column('file_description', sa.String(length=500), nullable=True))
    op.create_table_comment(
        'ut_file',
        '지식창고 File',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'ut_html_content',
        '지식창고',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'ut_resource_added_text',
        'Resource TEXT Type 부가정보',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'ut_resource_added_text',
        existing_comment='Resource TEXT Type 부가정보',
        schema=None
    )
    op.drop_table_comment(
        'ut_html_content',
        existing_comment='지식창고',
        schema=None
    )
    op.drop_table_comment(
        'ut_file',
        existing_comment='지식창고 File',
        schema=None
    )
    op.drop_column('ut_file', 'file_description')
    # ### end Alembic commands ###
