"""empty message

Revision ID: ef4ada906784
Revises: 7c2bc0bd343a
Create Date: 2021-07-14 18:29:29.886137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4ada906784'
down_revision = '7c2bc0bd343a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mo_was_instance_status_host_id_was_id_was_instance_id_key', 'mo_was_instance_status', type_='unique')
    op.create_unique_constraint(None, 'mo_was_instance_status', ['was_id', 'was_instance_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mo_was_instance_status', type_='unique')
    op.create_unique_constraint('mo_was_instance_status_host_id_was_id_was_instance_id_key', 'mo_was_instance_status', ['host_id', 'was_id', 'was_instance_id'])
    # ### end Alembic commands ###
