"""empty message

Revision ID: ef965f895a4b
Revises: 567931851832
Create Date: 2021-06-10 18:15:13.864465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef965f895a4b'
down_revision = '567931851832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ag_agent', sa.Column('token_expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ag_agent', 'token_expiration_date')
    # ### end Alembic commands ###
