"""empty message

Revision ID: f54d868a559b
Revises: 18dcfe9789d8
Create Date: 2022-07-28 12:19:33.336744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54d868a559b'
down_revision = '18dcfe9789d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mw_was_change_history', 'mw_was_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mw_was_change_history', 'mw_was_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
