"""empty message

Revision ID: fdb8d0501ae6
Revises: 25bd22f68d1b
Create Date: 2022-12-28 14:35:53.198799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdb8d0501ae6'
down_revision = '25bd22f68d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mw_web_server', sa.Column('monitor_now', postgresql.JSON(astext_type=sa.Text()), nullable=True, comment='서버현재상태'))
    op.add_column('mw_web_server', sa.Column('monitor_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='서버상태History'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mw_web_server', 'monitor_history')
    op.drop_column('mw_web_server', 'monitor_now')
    # ### end Alembic commands ###
